// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzoydakeyqjcpknstass.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6b3lkYWtleXFqY3BrbnN0YXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MDY5MzAsImV4cCI6MjA2ODE4MjkzMH0.nP0hgbjBtdySqwvduDA0c3Jp07hATQARExdj7uebD2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});